-- Baseline migration: consolidates the schema that was previously built up by
-- Hibernate's `ddl-auto=update` plus the three hand-written scripts under
-- backend/sql-scripts/ (07-add-roles-and-soft-delete, 08-add-fitting-data-columns,
-- 09-add-modular-jacket-columns). Table/column definitions below were generated
-- directly from the current JPA entity mappings (Hibernate schema-export), so
-- they are guaranteed to match what `spring.jpa.hibernate.ddl-auto=validate`
-- expects at startup.
--
-- This migration is NOT executed against the existing dev database: Flyway
-- baselines that database at this version instead (see application.properties,
-- spring.flyway.baseline-on-migrate/baseline-version). It only runs in full
-- against a genuinely empty database (fresh clone, CI, tests), producing the
-- same schema the dev database already has.

create table users (
    user_id bigint generated by default as identity,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    first_name varchar(255),
    last_name varchar(255),
    role varchar(255) not null check (role in ('ROLE_USER','ROLE_ADMIN')),
    active boolean not null,
    created_at timestamp(6),
    primary key (user_id)
);

create table clothing_items (
    item_id bigint generated by default as identity,
    owner_user_id bigint,
    name varchar(255) not null,
    description varchar(255),
    category varchar(255) not null check (category in ('TOP','BOTTOM','SHOES','ACCESSORY','JACKET','DRESS')),
    image_url varchar(500) not null,
    side varchar(255),
    persona_type varchar(255) not null check (persona_type in ('MALE','FEMALE')),
    transform_x float(53),
    transform_y float(53),
    transform_scale float(53),
    transform_scale_x float(53),
    transform_scale_y float(53),
    transform_rotation float(53),
    transform_width float(53),
    transform_height float(53),
    transform_opacity float(53),
    transform_flip_x boolean,
    transform_flip_y boolean,
    mask_top float(53),
    mask_left float(53),
    mask_width float(53),
    mask_height float(53),
    is_modular boolean,
    modular_data TEXT,
    is_active boolean,
    created_at timestamp(6),
    primary key (item_id)
);

create table outfits (
    outfit_id bigint generated by default as identity,
    owner_user_id bigint,
    name varchar(255) not null,
    description varchar(255),
    avatar_type varchar(255) not null check (avatar_type in ('MALE','FEMALE')),
    created_at timestamp(6),
    primary key (outfit_id)
);

create table outfit_items (
    outfit_item_id bigint generated by default as identity,
    outfit_id bigint,
    item_id bigint,
    slot varchar(255),
    item_order integer,
    position_x float(53),
    position_y float(53),
    scale_x float(53),
    scale_y float(53),
    rotation float(53),
    primary key (outfit_item_id)
);

alter table if exists clothing_items
    add constraint FKekvvgy2idqbvmm9gagrj8t2ot
    foreign key (owner_user_id)
    references users;

alter table if exists outfits
    add constraint FK9e6q0ahe1p7mthbq7x5cchtev
    foreign key (owner_user_id)
    references users;

alter table if exists outfit_items
    add constraint FKthcr3blfmr59mom14b0qwdwx6
    foreign key (item_id)
    references clothing_items;

alter table if exists outfit_items
    add constraint FK87wgrfdjuqofpa5kdypxybvyh
    foreign key (outfit_id)
    references outfits;

-- Extra indexes from the original 07-add-roles-and-soft-delete.sql script.
-- idx_users_email is redundant with the unique constraint on users.email above
-- (both were present on the live dev database), kept here for parity/history.
create unique index if not exists idx_users_email on users(email);
create index if not exists idx_users_active on users(active);
