-- Adds Collections (Task 33, Phase 7 pivot "Categories" feature). Named
-- "collections" at the DB/code level to avoid colliding with the existing
-- clothing_items.category column/ClothingCategory enum - UI copy still says
-- "Categories". A collection is private per its owner (Phase 7 open
-- question #2) and may hold a mix of individual clothing items and whole
-- outfits (#3, hence two separate join tables rather than one polymorphic
-- table), and an item/outfit may belong to several collections at once.

create table collections (
    collection_id bigint generated by default as identity,
    owner_user_id bigint,
    name varchar(255) not null,
    created_at timestamp(6),
    primary key (collection_id)
);

create table collection_items (
    collection_item_id bigint generated by default as identity,
    collection_id bigint,
    item_id bigint,
    primary key (collection_item_id)
);

create table collection_outfits (
    collection_outfit_id bigint generated by default as identity,
    collection_id bigint,
    outfit_id bigint,
    primary key (collection_outfit_id)
);

alter table if exists collections
    add constraint fk_collections_owner
    foreign key (owner_user_id)
    references users;

alter table if exists collection_items
    add constraint fk_collection_items_collection
    foreign key (collection_id)
    references collections;

alter table if exists collection_items
    add constraint fk_collection_items_item
    foreign key (item_id)
    references clothing_items;

alter table if exists collection_outfits
    add constraint fk_collection_outfits_collection
    foreign key (collection_id)
    references collections;

alter table if exists collection_outfits
    add constraint fk_collection_outfits_outfit
    foreign key (outfit_id)
    references outfits;

-- Prevents two collections with the same name (case-insensitive) for one
-- owner - Task 41's create/rename UI can rely on this instead of a racy
-- check-then-insert.
create unique index idx_collections_owner_name on collections(owner_user_id, lower(name));

-- Prevents redundant membership rows for the same item/outfit in the same
-- collection - membership is a pure set relationship, duplicates are
-- meaningless. The service layer already guards this in Java; these are
-- the DB-level backstop.
create unique index idx_collection_items_unique on collection_items(collection_id, item_id);
create unique index idx_collection_outfits_unique on collection_outfits(collection_id, outfit_id);
