-- Adds per-user persona display names (Task 60, Phase 9.5). Keyed by
-- (owner_user_id, persona_type) rather than fixed male_name/female_name
-- columns, so a future third AvatarType value needs no schema change here
-- - just a new possible row. Only stores overrides - a user with no row
-- for a given persona_type falls back to the frontend's own default
-- ("M Persona"/"F Persona"), so this table is never pre-seeded per
-- user/persona-type combination.

create table persona_display_names (
    persona_display_name_id bigint generated by default as identity,
    owner_user_id bigint not null,
    persona_type varchar(255) not null,
    display_name varchar(255) not null,
    primary key (persona_display_name_id)
);

alter table persona_display_names
    add constraint fk_persona_display_names_owner
    foreign key (owner_user_id)
    references users;

create unique index idx_persona_display_names_unique on persona_display_names(owner_user_id, persona_type);
