-- One-time password reset tokens (Task 21). Only a SHA-256 hash of the token is
-- stored, so a database leak can't be turned into working reset links.
create table password_reset_tokens (
    token_id bigint generated by default as identity,
    user_id bigint not null,
    token_hash varchar(64) not null unique,
    expires_at timestamp(6) not null,
    used_at timestamp(6),
    created_at timestamp(6) not null,
    primary key (token_id),
    constraint fk_password_reset_tokens_user
        foreign key (user_id) references users (user_id) on delete cascade
);

create index idx_password_reset_tokens_user_id on password_reset_tokens (user_id);
