-- Code-confirmed email/password changes (Task 79 follow-up): a "request" step
-- fully validates and stages the change here; a "confirm" step (a 6-digit
-- code emailed to the account's current address) applies it. One table for
-- both change types (a discriminator column), same reuse-not-duplicate
-- reasoning as persona_display_names covering both persona types.
create table pending_account_changes (
    change_id bigint generated by default as identity,
    user_id bigint not null,
    change_type varchar(20) not null check (change_type in ('EMAIL','PASSWORD')),
    -- Only one of these is set, depending on change_type.
    new_email varchar(255),
    new_password_hash varchar(255),
    -- Only the SHA-256 hash of the code is stored, same reasoning as
    -- password_reset_tokens.token_hash - a leaked table can't be turned into
    -- a working code.
    code_hash varchar(64) not null unique,
    attempt_count int not null default 0,
    expires_at timestamp(6) not null,
    used_at timestamp(6),
    created_at timestamp(6) not null,
    primary key (change_id),
    constraint fk_pending_account_changes_user
        foreign key (user_id) references users (user_id) on delete cascade
);

create index idx_pending_account_changes_user_type on pending_account_changes (user_id, change_type);
